version: 1.0.{build}

install:
   - nuget restore


build:
  project: ChainOfResposibility.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal

